##===- lib/HookPlacement/Makefile -----------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

LEVEL = ../..
LIBRARYNAME = TaintFlow
LOADABLE_MODULE = 1
USEDLIBS = 

include $(LEVEL)/Makefile.common

